Repository TDT4290-SDG-Ontology/SDG-ontology-visualizer, pull requests merged in 2021-09, with the labels that each got.

#3 Containerization
  .gitignore
  README.md
  backend/.dockerignore
  backend/.env.example
  backend/api.Dockerfile
  backend/database/conf/TK_SDG-config.ttl
  backend/database/graphdb.Dockerfile
  backend/database/ontology/SDG_Ontology.owl
  backend/docker-compose-backend.yml
  backend/docker-compose-db.yml
  backend/package-lock.json
  backend/src/routes/middleware/onError.ts
  backend/src/routes/ontologies.ts
  frontend/.dockerignore
  frontend/.eslintrc.js
  frontend/Dockerfile
  frontend/docker-compose.yml
  frontend/package-lock.json
  frontend/package.json
  quick_start_windows.bat
Labels: enhancement

#2 Bug eslint prettier conflict
  frontend/.eslintrc.js
  frontend/src/common/d3.ts
  frontend/src/common/regex.ts
  frontend/src/d3/GraphSimulation.ts
Labels: bug

#5 Feature/backend/authorization
  backend/.env.example
  backend/package.json
  backend/src/auth/credentials.ts
  backend/src/config.ts
  backend/src/database/getUserPasswordHash.ts
  backend/src/database/queries/getUserPasswordHash.ts
  backend/src/routes/authorization.ts
  backend/src/routes/index.ts
  backend/src/routes/middleware/verifyToken.ts
  backend/src/types/userTypes.ts
  backend/yarn.lock
  ontology/SDG_Ontology.owl
  utils/make_user/README.md
  utils/make_user/make_user.py
  utils/test_post/test.py
Labels: enhancement

#7 Feature/setup docker for development
  .github/workflows/main.yml
  README.md
  backend/api.Dockerfile
  backend/package-lock.json
  frontend/Dockerfile
  frontend/dev.Dockerfile
  frontend/docker-compose-dev.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/yarn.lock
Labels: enhancement

#8 Feature/ontology/identification of dummy data
  README.md
  backend/database/ontology/SDG_Ontology.owl
Labels: documentation, enhancement

#11 Feature/backend/data entry
  backend/database/ontology/SDG_Ontology.owl
  backend/src/database/getDataSeries.ts
  backend/src/database/index.ts
  backend/src/database/queries/getDataSeries.ts
  backend/src/database/queries/setData.ts
  backend/src/database/setData.ts
  backend/src/database/u4sscKpiMap.ts
  backend/src/database/u4ssc_kpi_map.json
  backend/src/routes/data.ts
  backend/src/routes/index.ts
  backend/src/routes/ontologies.ts
  backend/src/types/ontologyTypes.ts
  backend/src/types/routerTypes.ts
  backend/tsconfig.json
  backend/yarn.lock
Labels: enhancement
